### PR TITLE
Add an option to swap out TouchableWithoutFeedback for another component

### PR DESCRIPTION
**Pull request by brentvatne**
### Motivation

Sometimes people want to have different effects when the tab button is pressed, like a bounce effect in the Twitter app. This makes that pretty easy to do.

### Test plan

Try the example project.

### CODE REVIEW

**Comment by ericvicenti** [comment]
Only question, should it just be `buttonComponent` or `ButtonComponent`? Does it really need to be a getter?

Otherwise looks good to me!

Also I just realized that people could use this to render notification labels or badge counts on top of the icon.

**Comment by brentvatne** [comment]
@ericvicenti - I followed the convention from `tabBarComponent` and called it `tabBarButtonComponent`. Re: getter, I followed the existing pattern of doing this for getting label text etc. I considered making the button component an option that would apply to all buttons in the tab bar, but decided that there's no reason to limit people to that and just threw it on the `navigationOptions` instead.

**Comment by ericvicenti** [comment]
Ah, yeah that is definitely consistent with the rest of the tabs library.

**Comment by satya164** [comment]
Looks good!

**Comment by brentvatne** [comment]
CI failure seems to be unrelated 🤔

**Comment by fbartho** [comment]
I love this! I'm working with ReactXP and we have a custom Button component that has dynamic type support, and a variety of other enhancements. Swapping the button component helps us out a ton.

**Pull request merged**
